
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftCODEKWCODE EXIT KWrespuesta : ss : CODE KWs : EXIT'
    
_lr_action_items = {'CODE':([0,],[3,]),'EXIT':([0,],[4,]),'$end':([1,2,4,5,],[0,-1,-3,-2,]),'KW':([3,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'respuesta':([0,],[1,]),'s':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> respuesta","S'",1,None,None,None),
  ('respuesta -> s','respuesta',1,'p_respuesta','interprete_bomberos.py',55),
  ('s -> CODE KW','s',2,'p_res_completa','interprete_bomberos.py',62),
  ('s -> EXIT','s',1,'p_exit','interprete_bomberos.py',120),
]
